name: fihirana
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  sqflite: ^2.0.0+4
  provider: ^6.0.3
  http: ^1.2.1
  shared_preferences: ^2.0.13
  font_awesome_flutter: ^10.5.0
  get: ^4.6.6
  google_fonts: ^6.2.1
  flutter_secure_storage: ^9.2.2
  filter_list: ^1.0.3
  curved_navigation_bar: ^1.0.6
  liquid_swipe: ^3.1.0
  flutter_zoom_drawer: ^3.2.0
  awesome_notifications: ^0.9.3+1
  firebase_core: ^3.2.0
  cloud_firestore: ^5.1.0
  google_sign_in: ^6.2.1
  firebase_auth: ^5.1.2
  flutter_launcher_icons: ^0.13.1
  firebase_storage: ^12.1.1
  file_picker: ^8.0.6
  cached_network_image: ^3.4.0
  local_auth: ^2.3.0
  android_intent_plus: ^4.0.3
  path_provider: ^2.1.2
  turn_page_transition: ^0.3.0
  syncfusion_flutter_sliders: ^27.2.3
  dots_indicator: ^3.0.0
  flutter_svg: ^2.0.10+1
  flutter_colorpicker: ^1.1.0
  url_launcher: ^6.2.5
  package_info_plus: ^8.1.1
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/fonts/

flutter_launcher_icons:
  image_path_android: "assets/images/icon.png"
  image_path_ios: "assets/images/icon.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  adaptive_icon_background: "assets/images/icon.png" # only available for Android 8.0 devices and above
  adaptive_icon_foreground: "assets/images/icon.png" # only available for Android 8.0 devices and above
  adaptive_icon_monochrome: "assets/images/icon.png" # only available for Android 13 devices and above
  min_sdk_android: 23 # android min sdk min:16, default 21
  remove_alpha_ios: true
  background_color_ios: "#ffffff"
