name: fihirana
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  sqflite: ^2.0.0+4
  provider: ^6.0.3
  http: ^1.1.0
  shared_preferences: ^2.0.13
  font_awesome_flutter: ^10.5.0
  get: ^4.6.6
  google_fonts: ^4.0.4
  flutter_secure_storage: ^9.2.2
  filter_list: ^1.0.3
  curved_navigation_bar: ^1.0.6
  liquid_swipe: ^3.1.0
  flutter_zoom_drawer: ^3.2.0
  firebase_core: ^2.24.2
  cloud_firestore: ^4.13.6
  google_sign_in: ^6.2.1
  firebase_auth: ^4.16.0
  flutter_launcher_icons: ^0.13.1
  firebase_storage: ^11.5.6
  cached_network_image: ^3.3.0
  local_auth: ^2.1.7
  android_intent_plus: ^4.0.3
  path_provider: ^2.1.2
  turn_page_transition: ^0.3.0
  dots_indicator: ^3.0.0
  flutter_svg: ^2.0.9
  flutter_colorpicker: ^1.0.3
  url_launcher: ^6.2.2
  package_info_plus: ^4.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  loading_animation_widget: ^1.2.0+4
  flutter_phoenix: ^1.1.1
  awesome_notifications: ^0.10.1
  intl: ^0.20.2
  syncfusion_flutter_sliders: ^31.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/fonts/

flutter_launcher_icons:
  image_path_android: "assets/images/icon.png"
  image_path_ios: "assets/images/icon.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  adaptive_icon_background: "assets/images/icon.png" # only available for Android 8.0 devices and above
  adaptive_icon_foreground: "assets/images/icon.png" # only available for Android 8.0 devices and above
  adaptive_icon_monochrome: "assets/images/icon.png" # only available for Android 13 devices and above
  min_sdk_android: 23 # android min sdk min:16, default 21
  remove_alpha_ios: true
  background_color_ios: "#ffffff"
