name: Create Release

on:
  push:
    tags:
      - 'v*.*.*'  # Runs on tag pushes like v1.0.0, v2.5.3

permissions:
  contents: write
  packages: write

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Get dependencies
        run: flutter pub get

      - name: Disable Flutter Analytics
        run: flutter config --no-analytics

      # ----------------------
      # Generate App Icons
      # ----------------------
      - name: Generate App Icons
        run: flutter pub run flutter_launcher_icons:main

      # ----------------------
      # Setup Keystore
      # ----------------------
      - name: Setup Keystore
        run: |
          python -c "import base64; open('android/app/fihirana.jks','wb').write(base64.b64decode('${{ secrets.KEYSTORE_BASE64 }}'))"
          if [ ! -f "android/app/fihirana.jks" ]; then
            echo "Keystore file was not created"
            exit 1
          fi
          ls -l android/app/fihirana.jks

      # ----------------------
      # Setup Google Services JSON
      # ----------------------
      - name: Setup Google Services JSON
        run: |
          python -c "import base64; open('android/app/google-services.json','wb').write(base64.b64decode('${{ secrets.GOOGLE_JSON_BASE64 }}'))"
          mkdir -p android/app/src/release
          cp android/app/google-services.json android/app/src/release/google-services.json
      

      # ----------------------
      # Generate Changelog
      # ----------------------
      - name: Generate changelog
        id: changelog
        run: |
          PREVIOUS_TAG=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo "")
          if [ -z "$PREVIOUS_TAG" ]; then
            git log --pretty=format:"* %s" > CHANGELOG.md
          else
            git log --pretty=format:"* %s" $PREVIOUS_TAG..HEAD > CHANGELOG.md
          fi
          echo "CHANGELOG created:"
          cat CHANGELOG.md

      # ----------------------
      # Build Flutter APK
      # ----------------------
      - name: Build APKs
        run: flutter build apk --release --split-per-abi

      # ----------------------
      # Create GitHub Release
      # ----------------------
      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build/app/outputs/flutter-apk/*.apk
          token: ${{ secrets.GITHUB_TOKEN  }}
          name: Release ${{ github.ref_name }}
          body_path: CHANGELOG.md
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}